title: Fastlist Docs
description: Fastlist 用户指南，模版开发指南
theme: just-the-docs
baseurl: /fastlist-doc
url: https://seadfeng.github.io

aux_links:
  Doc Repository: https://github.com/seadfeng/fastlist-doc


color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache